version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: aihub-minio
    ports:
      - "9000:9000"  # API endpoint
      - "9001:9001"  # Console endpoint
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # Criar bucket automaticamente após MinIO iniciar
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/aihub-files --ignore-existing;
      /usr/bin/mc anonymous set public myminio/aihub-files;
      echo 'Bucket criado e configurado com sucesso!';
      "

volumes:
  minio-data:
    driver: local