[phases.setup]
nixPkgs = ["nodejs_22", "libuuid", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "node scripts/railway-emergency-build.js"
]

[start]
cmd = "pnpm run start"

[variables]
NODE_OPTIONS = "--max-old-space-size=50176 --optimize-for-size"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_SERVICE_MODE = "server"
DISABLE_SENTRY = "true"
ANALYZE = "false"
SKIP_ENV_VALIDATION = "true"