[phases.setup]
nixPkgs = ["nodejs_20", "libuuid"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run prebuild",
  "pnpm run build:railway"
]

[start]
cmd = "pnpm run start"

[variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_SERVICE_MODE = "server"