[build]
builder = "nixpacks"

[deploy]
startCommand = "NODE_OPTIONS='--max-old-space-size=4096' pnpm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3