[build]
builder = "nixpacks"
buildCommand = "node scripts/railway-ultralight-build.js"

[deploy]
startCommand = "NODE_OPTIONS='--max-old-space-size=32768' pnpm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_OPTIONS = "--max-old-space-size=40960"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_PUBLIC_SERVICE_MODE = "server"
DISABLE_SENTRY = "true"
ANALYZE = "false"
SKIP_ENV_VALIDATION = "true"